// components/style/tab/LibraryStyles.ts
import { RADIUS } from '@/constants/tab/library';
import type { Palette } from '@/theme/ThemeProvider';
import { StyleSheet } from 'react-native';

export const LibraryStyles = (p: Palette) =>
  StyleSheet.create({
    safe: { flex: 1, backgroundColor: p.bg },
    container: { flex: 1, backgroundColor: p.bg },

    headerWrap: { backgroundColor: p.bg, paddingBottom: 8 },
    titleRow: {
      paddingHorizontal: 16,
      paddingBottom: 8,
      flexDirection: 'row',
      alignItems: 'center',
    },
    title: { fontSize: 24, fontWeight: '800', color: p.text, flex: 1 },
    sortBtn: { flexDirection: 'row', alignItems: 'center', padding: 8 },
    sortText: { marginLeft: 6, color: p.text, fontWeight: '600' },

    mePill: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: RADIUS.pill,
      borderWidth: 1,
      borderColor: p.cardBorder,
      marginRight: 6,
      backgroundColor: p.card,
    },
    mePillText: { marginLeft: 6, fontWeight: '700', color: p.text },

    upsell: {
      marginHorizontal: 16,
      marginBottom: 8,
      padding: 10,
      borderRadius: RADIUS.md,
      borderWidth: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    upsellText: { flex: 1, color: p.text },

    searchBox: {
      marginHorizontal: 16,
      marginBottom: 8,
      borderRadius: RADIUS.md,
      backgroundColor: p.cardBorder,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      height: 44,
    },
    searchInput: { flex: 1, marginLeft: 8, color: p.text },

    gradeList: { paddingHorizontal: 12, paddingVertical: 6 },
    gradeChip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: RADIUS.pill,
      marginHorizontal: 4,
      borderWidth: 1,
    },
    gradeText: { fontWeight: '700' },

    card: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 14,
      backgroundColor: p.card,
      borderRadius: RADIUS.lg,
      marginHorizontal: 16,
      marginVertical: 8,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: p.cardBorder,
      elevation: 0,
    },
    cardIcon: {
      width: 54,
      height: 54,
      borderRadius: 14,
      backgroundColor: p.cardBorder,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
      position: 'relative',
    },
    lockBadge: {
      position: 'absolute',
      right: -6,
      top: -6,
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: '#EF4444',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: p.card,
    },
    cardTitle: { fontSize: 16, fontWeight: '700', color: p.text },
    premiumPill: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: RADIUS.pill,
      borderWidth: 1,
      marginLeft: 8,
      gap: 4,
    },
    premiumText: { fontSize: 11, fontWeight: '800', color: p.text },

    cardSub: { fontSize: 13, color: p.textMuted, marginTop: 2 },

    tagRow: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 6 },
    tagChip: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      backgroundColor: p.pillBg,
      borderRadius: RADIUS.pill,
      marginRight: 6,
      marginBottom: 6,
      borderWidth: 1,
      borderColor: p.pillBorder,
    },
    tagText: { fontSize: 11, color: p.textFaint, fontWeight: '600' },

    emptyWrap: { alignItems: 'center', paddingTop: 48 },
    emptyText: { color: p.textMuted, marginTop: 8 },

    modalBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.35)',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 20,
    },
    modalCard: {
      width: '100%',
      maxWidth: 420,
      borderRadius: 16,
      borderWidth: 1,
      padding: 16,
    },
    modalIcon: {
      width: 48,
      height: 48,
      borderRadius: 24,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: p.cardBorder,
      alignSelf: 'center',
      marginBottom: 12,
    },
    modalTitle: { fontSize: 18, fontWeight: '800', color: p.text, textAlign: 'center' },
    modalDesc: { color: p.textMuted, marginTop: 6, textAlign: 'center' },
    modalRow: { flexDirection: 'row', gap: 10, marginTop: 16 },
    modalBtn: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 12,
      alignItems: 'center',
      borderWidth: 1,
    },
    modalBtnText: { fontWeight: '800' },
  });
